name: Lint

on:
  pull_request:
  push:

jobs:
  fmt:
    name: fmt
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2024-06-10
          components: rustfmt

      - name: cargo fmt
        run: cargo fmt --all -- --check

  clippy:
    name: clippy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2024-06-10
          components: clippy

      - name: cargo clippy
        run: cargo clippy --all

  udeps:
    name: udeps
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2024-06-10

      - name: Install udeps
        run: cargo install --git https://github.com/est31/cargo-udeps --locked

      - name: cargo udeps
        run: cargo udeps

      - name: Install taplo
        uses: baptiste0928/cargo-install@v3
        with:
          crate: taplo-cli
      - run: taplo fmt --check
